sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
matrix:
  include:
    - node_js: "6"
    - node_js: "4"
    - node_js: "0.10"
before_script:
  - npm prune
